name: Master Sync

on:
  workflow_dispatch:

jobs:

  intervals:
    uses: ./.github/workflows/sync.yml
    secrets: inherit

  dropbox-fit:
    needs: intervals
    uses: ./.github/workflows/sync_and_process.yml
    secrets: inherit
